name: Build and Release Python Package with uv

on:
  push:
    tags:
      - 'v*.*.*'  # Semantic version tags like v1.2.3

permissions:
  contents: write

jobs:
  guard:
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.check.outputs.should_release }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Check if tag is on default branch
      id: check
      run: |
        TAG_COMMIT=$(git rev-list -n 1 ${{ github.ref_name }})
        DEFAULT_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
        BRANCH_COMMIT=$(git rev-parse origin/$DEFAULT_BRANCH)

        echo "Tag commit: $TAG_COMMIT"
        echo "Default branch ($DEFAULT_BRANCH) commit: $BRANCH_COMMIT"

        if [ "$TAG_COMMIT" = "$BRANCH_COMMIT" ]; then
          echo "should_release=true" >> $GITHUB_OUTPUT
        else
          echo "should_release=false" >> $GITHUB_OUTPUT
        fi

  build-and-release:
    needs: guard
    if: needs.guard.outputs.should_release == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Extract version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    - name: Verify uv installation
      run: uv --version
    - name: Set version in pyproject.toml
      run: |
        sed -i "s/^version = .*/version = \"${VERSION}\"/" pyproject.toml
    - name: Build package
      run: |
        cd pkgs/myproj
        uv build
    - name: Create GitHub Release and upload artifacts
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          Automated release for version ${{ github.ref_name }}.
        files: |
          pkgs/myproj/dist/*.whl
          pkgs/myproj/dist/*.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
